# Generated by Django 6.0 on 2026-01-05 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(help_text='Contoh: 111 (Kas), 411 (Pendapatan)', max_length=20, unique=True)),
                ('nama', models.CharField(help_text='Contoh: Kas, Modal, Beban Gaji', max_length=100)),
                ('kategori', models.CharField(choices=[('ASSET', 'Harta (Aktiva)'), ('LIABILITY', 'Kewajiban (Utang)'), ('EQUITY', 'Modal (Ekuitas)'), ('REVENUE', 'Pendapatan'), ('EXPENSE', 'Beban')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('uraian', models.CharField(help_text='Keterangan transaksi', max_length=255)),
                ('nominal', models.DecimalField(decimal_places=0, help_text='Jumlah Rupiah', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akun_debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_entries', to='finance.akun', verbose_name='Akun Debit')),
                ('akun_kredit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kredit_entries', to='finance.akun', verbose_name='Akun Kredit')),
            ],
            options={
                'verbose_name_plural': 'Jurnal Umum',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
